### PR TITLE
Make TemplatesMonad generic instance overlappable

### PR DESCRIPTION
**Pull request by soareschen**
This change is [Reviewable](https://reviewable.io/reviews/scrive/kontrakcja-templates/2)

### CODE REVIEW

**Comment by arybczak** [comment]
Kontrakcja will not compile because `ToSElem` class instances are utterly broken. I'll fix them.

**Comment by arybczak** [comment]
Ok, I got rid of `ToSElem` class redefined here and made use of the one from `HStringTemplates`.

This is a remain from ancient times when kontrakcja used ByteString for text, so these utf8 aware conversions were needed. Nowadays the only thing that's passed to templates as ByteString are Base64 encoded images/signatures, so it's safe to remove it.

**Comment by soareschen** [comment]
LGTM. My local tests on kontrakcja are passing.

**Review by Siprj — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scrive/kontrakcja-templates/2)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @arybczak and @Siprj)

**Review by Siprj — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scrive/kontrakcja-templates/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arybczak)

**Comment by arybczak** [comment]
I added a few more instances and corrected the one for `SElem`. I also sent the maintainer of `HStringTemplate` a patch with these so let's wait a few more days, I'd hope he includes them in a new release and we don't have to supply orphans.

**Pull request merged**
